# Generated by Django 2.0.6 on 2018-11-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Image',
            field=models.ImageField(default='default.jpg', upload_to='product_images'),
        ),
    ]
