# Generated by Django 2.0.7 on 2019-01-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181109_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
