# Generated by Django 2.0.7 on 2019-04-21 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190421_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='prix',
        ),
    ]
