# Generated by Django 2.0.7 on 2019-04-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_products_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='nom',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
